#!/bin/bash

input="urlsForSQL.txt"

echo "path,nb form/site"

while IFS= read -r line
do
  echo -n "$line,";
  ssh -n wwp-prod -- "wp db query --path=$line 'SELECT COUNT(*) FROM wp_wpforms_entries GROUP BY form_id;' --skip-column-names"
done < "$input"
