#!/bin/bash

input="urlsForSQL.txt"

while IFS= read -r line
do
  echo -n "$line,";
  ssh -n wwp-prod -- "wp db query --path=$line 'SELECT DISTINCT(wp_posts.post_content), COUNT(*) FROM wp_wpforms_entries
INNER JOIN wp_posts ON wp_wpforms_entries.form_id=wp_posts.ID GROUP BY wp_wpforms_entries.form_id;' --skip-column-names"
done < "$input"
